### PR TITLE
Try branch/PR builds again.

### PR DESCRIPTION
**Pull request by ZryletTC**

### CODE REVIEW

**Comment by ZryletTC** [comment]
Currently the PyPI deployment runs when commits are tagged on a non-master branch.
This is shown from the v0.6.1 release which tagged a commit from the prtest2 branch.
Apparently, the `tags: true` line in [the yaml](https://github.com/hhslepicka/pcds-ci-helpers/blob/pypi/travis/pypi-upload.yml#L12) ignores the `branch: master` line so I'm not sure if there's a good way to stop it.

Should we just hope nobody'll tag a branch they shouldn't?

**Comment by ZryletTC** [comment]
Also the docs apparently don't build on tagged builds by default. Am I wrong for thinking that we'd want them to? When we create a new release, we'd want the new version number reflected in the docs, right?

I can add these deploy on tagged builds by adding `--build-tags` to [the yaml](https://github.com/hhslepicka/pcds-ci-helpers/blob/a2b64857013136114e3ccc542a742a4380a83b91/travis/doctr-upload.yml#L21)

**Comment by ZryletTC** [comment]
@hhslepicka What do you think?

**Comment by hhslepicka** [comment]
PyPI
----
For the PyPI Upload, do you mind to try with:
- insert this after the `name` field:
```
    if: branch = master AND tag IS present
```
- remove this: https://github.com/hhslepicka/pcds-ci-helpers/blob/pypi/travis/shared_configs/pypi-upload.yml#L11-L12

Docs
-----
You are absolutely right. We need the build for merges to master and tags.

General
--------
I believe that you can remove this line here (https://github.com/hhslepicka/testproject1234/blob/master/.travis.yml#L32-L33) at the Deploy and let the stages decide if they should run or not.

**Comment by ZryletTC** [comment]
> ## PyPI
> For the PyPI Upload, do you mind to try with
> ```
>     if: branch = master AND tag IS present
> ```
The issue with that is that on tag builds, the value of `branch` is set to the tag name, so it won't be master and that condition will always fail.

> ## Docs
> You are absolutely right. We need the build for merges to master and tags.
Cool, I've already enabled it.

> ## General
> I believe that you can remove this line here (https://github.com/hhslepicka/testproject1234/blob/master/.travis.yml#L32-L33) at the Deploy and let the stages decide if they should run or not.
Is there any reason to run deploy if this condition is not satisfied?

**Comment by hhslepicka** [comment]
You are correct... Here is a reference to that: https://docs.travis-ci.com/user/deployment-v2/conditional#tag

In this case the best we can hope for is that people push tags only to master. 🤞 
That should be sufficient for now.

On a different note, can we also get a template for the Anaconda upload?
Different than PyPI it will have:
- push to master: send it to DEV channel
- tag: send it to TAG channel

**Comment by ZryletTC** [comment]
Yeah sure, I'll add it in.

**Pull request closed without merging**
